const productos = [
    {id:1, nombre:"Alisa", precio:850,  tipo:"N14", imagen:'../imagenes/alisa.png', cantidad:1, prod: "maceta"},
    {id:2, nombre:"White", precio:1200, tipo:"N°16", imagen:'../imagenes/white.png' , cantidad:1, prod: "maceta"},
    {id:3, nombre:"Golden", precio:850, tipo:"N14", imagen:'../imagenes/golden.png', cantidad:1, prod: "maceta"},
    {id:4, nombre:"Wooden Like" , precio:450, tipo:"N°8", imagen:'../imagenes/m6.png', cantidad:1, prod: "maceta"},
    {id:5, nombre:"Daisy", precio:680, tipo:"N°12", imagen:'../imagenes/maceta amarrilla.png', cantidad:1, prod: "maceta"},
    {id:6, nombre:"Marga", precio:680, tipo:"N°12", imagen:'../imagenes/m5.png', cantidad:1, prod: "maceta"},
    {id:7, nombre:"Mate", precio:680, tipo:"N°12", imagen:'../imagenes/maceta mate.png', cantidad:1, prod: "maceta"},
    {id:8, nombre:"Fatima", precio:850, tipo:"N14", imagen:'../imagenes/m7.png', cantidad:1, prod: "maceta"},
    {id:9, nombre:"Brains", precio:680, tipo:"N°12", imagen:'../imagenes/macetabrains.png', cantidad:1, prod: "maceta"},
    {id:10, nombre:"Llama", precio:680, tipo:"N°12", imagen:'../imagenes/llama.png', cantidad:1, prod: "maceta"},
    {id:11, nombre:"Homero", precio:750, tipo:"N°10",imagen: '../imagenes/m4.png', cantidad:1, prod: "maceta"},
    {id:12, nombre:"Perfect", precio:450, tipo:"N°8", imagen:'../imagenes/m8.png', cantidad:1, prod: "maceta"},
    {id:13,nombre:"Parma",  precio:600, tipo:"Tussor Rayas", imagen:'../imagenes/almohadones parma.jpeg', cantidad:1, prod: "almohadon"},
    {id:14,nombre:"Invierno Pack x3",  precio:2300,  tipo:"Piel Sintetica, Tussor", imagen:'../imagenes/almo.jpg', cantidad:1, prod: "almohadon"},
    {id:15,nombre:"Vikings Pack x3", precio: 2300,  tipo:"Piel Sintetica, Tussor", imagen:'../imagenes/pakx3.png', cantidad:1, prod: "almohadon"},
    {id:16,nombre:"Tussor Pack x3", precio:1950, tipo:"Tussor Liso", imagen:'../imagenes/car5.jpg', cantidad:1, prod: "almohadon"},
    {id:17,nombre:"Tussor silla", precio:440, tipo:"Tussor Liso", imagen:'../imagenes/almopra silla.png', cantidad:1, prod: "almohadon"},
    {id:18,nombre:"Grey Pack x2",  precio:2200, tipo:"Piel Sintetica, Tussor Print", imagen:'../imagenes/amoha gris.jpg', cantidad:1, prod: "almohadon"},
    {id:19,nombre:"Tussor",  precio:440,  tipo:"Tussor Liso", imagen:'../imagenes/tussor.png', cantidad:1, prod: "almohadon"},
    {id:20,nombre:"Pack Bohemian",  precio:2100, tipo: "Tussor Rayas, Decorado", imagen:'../imagenes/pack 3 boho.webp', cantidad:1, prod: "almohadon"},
    {id:21,nombre:"Della",  precio:1500, tipo: "Seda", imagen:'../imagenes/della.jpg', cantidad:1, prod: "almohadon"}
]